import { StyleSheet } from "react-native";

const Styles = StyleSheet.create({
  background: {
    alignItems: "center",
  },
  titulo: {
    width: "100%",
    height: 80,
    backgroundColor: "#c8c8c8",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 10,
    borderRadius: 5,
    flexDirection: "row",
    flexWrap:"wrap",
  },
  buttons: {
    backgroundColor: "#77e681",
    padding:"2%",
    borderRadius: 5,
    height:"100%",
    width:"15%",
    alignItems: "center",
    justifyContent: "center",
  },
  buttonsX: {
    backgroundColor: "#ff6969",
    padding:"2%",
    borderRadius: 5,
    height:"100%",
    width:"15%",
    alignItems: "center",
    justifyContent: "center",
  },
  listItems: {
    width: 330,
    height: 50,
    backgroundColor: "#c8c8c8",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
    borderRadius: 10,
  },
  list: {
    width: "90%",
    height: 650,
    backgroundColor: "#eaeaea",
    alignItems: "center",
    marginVertical: 40,
    borderRadius: 10,
  },
  listaNombre: {
    width: "100%",
    justifyContent: "center",
    marginVertical: 5,
    borderRadius: 5,
    flexDirection: "row",
  },
  subtitulos: {
    flexDirection: "row",
    left:30,
    fontSize:23,
  },
  textSpace: {
    fontSize:12,
    fontWeight:"bold",
    height:40,
    width:175,
    textAlign:"center",
    marginHorizontal:2,
  },
  newListName: {
    flexDirection: "row",
    height: 350,
    width: "100%",
    justifyContent: "space-between",
    paddingHorizontal:"5%",
  },
  newListItems: {
    width:"47%",
    height: "20%",
    backgroundColor: "#c8c8c8",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginVertical: "5%",
    textAlign:"center",
    paddingTop:"2%",
  },
  datePicker: {
    flexDirection:"row",
    marginVertical: "5%",
    justifyContent: "space-between",
  },
  textInput: {
    marginHorizontal:8,
    fontSize:15,
    textAlign:"center",
  },
  newListinput: {
    width:"90%",
    height: 80,
    backgroundColor: "#c8c8c8",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginVertical: "5%",
    textAlign:"center",
    paddingTop:"2%",
    bottom:270,
  },
  buttonInput: {
    width:"90%",
    height: 60,
    backgroundColor: "#92f79b",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 10,
    marginVertical: "5%",
    textAlign:"center",
    paddingTop:"2%",
    bottom:295,
  },
  listNew: {
    width: "90%",
    height: 270,
    backgroundColor: "#eaeaea",
    alignItems: "center",
    marginVertical: 40,
    borderRadius: 10,
  },
  scroll: {
    width: "90%",
    height: 10,
  },
  personasItems: {
    width: 280,
    height: 50,
    backgroundColor: "#c8c8c8",
    alignItems: "center",
    justifyContent: "space-between",
    marginVertical: 5,
    borderRadius: 10,
    flexDirection:"row",
    paddingLeft:30,
  },
  searchMenu: {
    width: 280,
    height: 240,
    backgroundColor: "#bfbfbf",
    alignItems: "center",
    borderRadius: 10,
    paddingTop: 10,
  },
  personasButon: {
    width: 280,
    height: 50,
    backgroundColor: "#77e681",
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 5,
    borderRadius: 10,
    flexDirection:"row",
  },
  ajustes: {
    backgroundColor:"#ff6969",
    width:"100%",
    borderBottomStartRadius:10,
    borderBottomEndRadius:10,
    height:30,
    alignItems: "center",
    justifyContent: "center",
  },
  unlink: {
    backgroundColor: "#ff6969",
    borderRadius: 5,
    height:"100%",
    width: 135,
    alignItems: "center",
    justifyContent: "center",
  },
  ajustesList: {
    backgroundColor:"#ff6969",
    width:"100%",
    borderBottomStartRadius:10,
    borderBottomEndRadius:10,
    height:30,
    alignItems: "center",
    justifyContent: "center",
    bottom: 0,
  },
  unlinkList: {
    backgroundColor: "#ff6969",
    padding:"2%",
    borderRadius: 5,
    height:"100%",
    width: 150,
    alignItems: "center",
    justifyContent: "center",
    bottom: 21,
    left: 90,
  },
});

export default Styles;
